/** Decision record — a player-facing choice generated by an event or simulation trigger. */

export interface DecisionChoice {
  id: string;
  label: string;
  description: string;
  /** Human-readable preview of expected outcomes shown before the player chooses. */
  consequences: string[];
}

export interface DecisionRecord {
  id: string;
  date: { month: string; year: number };
  title: string;
  description: string;
  choices: DecisionChoice[];
  selectedChoice: string | null;
  relatedEventId: string | null;
  /** Ids of outcome entities applied after resolution. */
  consequences: string[];
  resolved: boolean;
}
