// ── Life status ───────────────────────────────────────────────────────────────

export type LifeStatus =
  | 'Excelente'
  | 'Bom'
  | 'Normal'
  | 'Precisa de Atenção'
  | 'Crítico';

// ── History entry ─────────────────────────────────────────────────────────────

export interface LifeHistoryEntry {
  /** Unique per animal per month: `${animalId}-${month}-${year}` */
  id: string;
  month: string;
  year: number;
  /** Human-readable note generated by the service. */
  note: string;
  weightDelta: number;
  conditionDelta: number;
  stressDelta: number;
}

// ── Animal life state ─────────────────────────────────────────────────────────

export interface AnimalLifeState {
  animalId: string;
  ageMonths: number;
  bodyCondition: number;    // 0-100
  hydration: number;        // 0-100
  stress: number;           // 0-100
  fatigue: number;          // 0-100
  happiness: number;        // 0-100
  dominance: number;        // 0-100
  socialRank: number;       // 0-100
  health: number;           // 0-100
  fertility: number;        // 0-100
  weight: number;           // kg
  hornDevelopment: number;  // 0-100
  muscleCondition: number;  // 0-100
  history: LifeHistoryEntry[];
}
